spring:
  application:
    name: management
  app:
    jwt-secret: ${JWT_SECRET}
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-2
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

app:
  awsServices:
    bucketName: gtp-group-three-lms
management:
  endpoints:
    web:
      exposure:
        exclude: 'health,metrics,info'
  httpexchanges:
    recording:
      enabled: true

server:
  port: ${SERVER_PORT}
eureka:
  client:
    enabled: false