spring:

  app:
    jwtSecret: ${JWT_SECRET}
  application:
    name: service-provider-profile

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB

aws:
  accessKeyId: ${S3_ACCESS_KEY_ID}
  secretAccessKey: ${S3_SECRET_ACCESS_KEY}
  s3:
    bucketName: ${BUCKET_NAME}
    region: us-east-2

server:
  port: ${PROD_PORT:8050}

management:

  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka-server:
  port: ${EUREKA_PORT}
  hostname: ${EUREKA_HOSTNAME}

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-server.hostname}:${eureka-server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
      hostname: ${EUREKA_HOSTNAME}
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}

