services:
  authservice:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/authservice:latest
    container_name: auth-service-container
    restart: on-failure:3
    ports:
      - "9090:9090"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.authservice.env
    volumes:
      - prox-volume:/app/data

  eurekaserver:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/eurekaserver:latest
    container_name: eureka-server-container
    restart: on-failure:3
    ports:
      - "8761:8761"
    networks:
      - proximity-finder-network
      - training-shared-network
    volumes:
      - prox-volume:/app/data

  management:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/management:latest
    container_name: management-service-container
    restart: on-failure:3
    ports:
      - "9092:9092"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.management.env
    volumes:
      - prox-volume:/app/data

  provider-profile-service:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/provider-profile-service:latest
    container_name: provider-profile-service-container
    restart: on-failure:3
    ports:
      - "9093:9093"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.provider-profile-service.env
    volumes:
      - prox-volume:/app/data

  gatewayserver:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/gatewayserver:latest
    container_name: gatewayserver-container
    restart: on-failure:3
    ports:
      - "9094:9094"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.gatewayserver.env
    volumes:
      - prox-volume:/app/data

  help-and-support:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/help-and-support:latest
    container_name: help-and-support-container
    restart: on-failure:3
    ports:
      - "9095:9095"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.help-and-support.env
    volumes:
      - prox-volume:/app/data

  request-management:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/request-management:latest
    container_name: request-management-container
    restart: on-failure:3
    ports:
      - "9096:9096"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.request-management.env
    volumes:
      - prox-volume:/app/data

  notification-service:
    image: 909544387219.dkr.ecr.eu-west-1.amazonaws.com/notification-service:latest
    container_name: notification-service-container
    restart: on-failure:3
    ports:
      - "9097:9097"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./.notification-service.env
    volumes:
      - prox-volume:/app/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-container
    restart: on-failure:3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - proximity-finder-network
      - training-shared-network
    volumes:
      - prox-volume:/app/data

networks:
  proximity-finder-network:
    driver: bridge
  training-shared-network:
    driver: bridge

volumes:
  prox-volume: