INSERT INTO faq (question, answer, group_id)
VALUES
         ('What is a service seeker?', 'A seeker is someone looking for services on our platform.', 1),
         ('How do I register as a seeker?', 'You can register using your email and a valid phone number.', 1),
         ('How do I search for services?', 'Use the search bar to find services by category or location.', 1),
         ('Can I contact multiple providers?', 'Yes, you can contact as many providers as you need.', 1),
         ('Is there a fee for seekers?', 'No, registering as a seeker is free.', 1),
         ('Can I save a provider for future reference?', 'Yes, use the "Favorite" feature to save providers.', 1),
         ('How do I rate a provider?', 'After availing a service, you can leave a rating on the provider''s profile.', 1),
         ('What happens if I am unhappy with a service?', 'You can report the issue through the platform''s feedback form.', 1),
         ('Can I cancel a service request?', 'Yes, cancellation is possible before the service starts.', 1),
         ('How do I verify the provider''s credentials?', 'Providers'' profiles display verified badges if their credentials are validated.', 1),
         ('What happens if a provider doesn’t respond?', 'You can choose another provider or contact support.', 1),
         ('Can I book a service for someone else?', 'Yes, you can book services for family or friends.', 1),
         ('What is the refund policy for seekers?', 'Refund policies depend on the provider''s terms.', 1),
         ('How do I update my profile information?', 'Go to your profile settings to edit your details.', 1),
         ('Can I leave feedback for a provider?', 'Yes, feedback helps improve the platform and providers'' services.', 1),
         ('What is the response time for providers?', 'Response times vary; look for average response time on the provider''s profile.', 1),
         ('How do I track ongoing service requests?', 'Track requests from your dashboard under "My Requests".', 1),
         ('Are there reviews for providers?', 'Yes, you can read reviews left by other seekers.', 1),
         ('What payment methods are accepted?', 'Payment methods include credit cards, PayPal, and more.', 1),
         ('Is there customer support for seekers?', 'Yes, our support team is available 24/7 to assist you.', 1);
INSERT INTO faq (question, answer, group_id)
VALUES
         ('What is a service provider?', 'A provider offers services to seekers on our platform.', 2),
         ('How do I register as a provider?', 'Register with your business details and a valid email address.', 2),
         ('Are there fees for providers?', 'Providers pay a small commission for each completed service.', 2),
         ('Can I upload a portfolio?', 'Yes, you can showcase your work through the portfolio section.', 2),
         ('How do I get more service requests?', 'Maintain good ratings and regularly update your profile.', 2),
         ('Can I set my availability?', 'Yes, use the calendar feature to set your working hours.', 2),
         ('What is a "Featured Provider"?', 'Featured Providers appear at the top of search results.', 2),
         ('How do I become a Featured Provider?', 'Featured status is achieved through high ratings and platform compliance.', 2),
         ('Can I decline service requests?', 'Yes, providers can decline requests if they are unavailable.', 2),
         ('What happens if a seeker cancels the request?', 'If cancellation occurs within your policy limits, you may charge a cancellation fee.', 2),
         ('How do I update my pricing?', 'Go to your profile settings to adjust pricing.', 2),
         ('Can I message seekers directly?', 'Yes, you can communicate through the platform''s messaging system.', 2),
         ('What is the verification process for providers?', 'Submit your credentials for review to get verified.', 2),
         ('Are there penalties for canceling a booking?', 'Yes, cancellations may result in penalties depending on the circumstances.', 2),
         ('How do I withdraw my earnings?', 'Withdraw earnings through the "Payments" section in your dashboard.', 2),
         ('What are the best practices for providers?', 'Be responsive, maintain good ratings, and offer high-quality services.', 2),
         ('How can I promote my services?', 'Use the "Promotions" feature to advertise your services.', 2),
         ('Can I manage multiple services?', 'Yes, add and manage multiple services through your profile.', 2),
         ('What happens if I get a negative review?', 'Respond professionally and work on improving your services.', 2),
         ('Is customer support available for providers?', 'Yes, we have a dedicated support team for providers.', 2);
INSERT INTO faq (question, answer, group_id)
VALUES
         ('Is the platform free to use?', 'Yes, the platform is free for seekers.', 3),
         ('How do I report a technical issue?', 'Use the "Contact Us" section to report issues.', 3),
         ('Can I reset my password?', 'Yes, click on "Forgot Password" to reset it.', 3),
         ('Is my data safe on the platform?', 'Yes, we prioritize user data security with encryption.', 3),
         ('How can I delete my account?', 'Send a request through the "Delete Account" option in settings.', 3),
         ('What services are available on the platform?', 'The platform offers a wide range of services across categories.', 3),
         ('Can I refer friends to the platform?', 'Yes, use the referral program to invite your friends.', 3),
         ('Are there any discounts?', 'Discounts are available periodically; check the Promotions section.', 3),
         ('How do I update my profile?', 'Go to the Profile section and click "Edit."', 3),
         ('What are the platform''s working hours?', 'The platform is available 24/7.', 3),
         ('How do I contact support?', 'Reach out through the "Help" section or via email.', 3),
         ('Are there any terms and conditions?', 'Yes, read the Terms and Conditions on our website.', 3),
         ('Can I use the platform on mobile?', 'Yes, download our mobile app from the App Store or Google Play.', 3),
         ('How do I give feedback on the platform?', 'Use the "Feedback" section to share your thoughts.', 3),
         ('What happens during platform maintenance?', 'You will be notified of maintenance in advance.', 3),
         ('How do I check my notifications?', 'Notifications are accessible from your dashboard.', 3),
         ('Can I recover a deleted account?', 'No, account deletion is permanent.', 3),
         ('Does the platform support multiple languages?', 'Yes, the platform is available in several languages.', 3),
         ('Are there tutorials for using the platform?', 'Yes, tutorials are available in the "Help" section.', 3),
         ('What is the refund policy for subscription fees?', 'Refunds are issued based on our policy. Contact support for more details.', 3);
