spring:
  application:
    name: request-management-service
  app:
    jwtSecret: ${JWT_SECRET}

  rabbitmq:
    host: ${HOST_NAME:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:5672}
    exchange:
      name: booking-exchange
    queue:
      name: bookings-queue
    routing:
      key: booking.status.changed


  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${SERVER_PORT}

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_KEY}
  s3:
    bucketName: ${BUCKET_NAME}
    region: ${AWS_REGION}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_HOSTNAME}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true


